<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_</name>
   <tag></tag>
   <elementGuidId>3c0cb4e7-ece3-436b-9ef4-a60b2831131b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_720kb-datepicker-default-button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>⟩</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eventDialog&quot;)/div[@class=&quot;ng-modal-dialog&quot;]/div[@class=&quot;ng-modal-dialog-content&quot;]/div[@class=&quot;edit-box row ng-scope&quot;]/div[@class=&quot;input-field col s12&quot;]/div[@class=&quot;col s8&quot;]/datepicker[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;_720kb-datepicker-calendar _720kb-datepicker-open&quot;]/div[@class=&quot;_720kb-datepicker-calendar-header&quot;]/div[@class=&quot;_720kb-datepicker-calendar-header-right&quot;]/a[@class=&quot;_720kb-datepicker-calendar-month-button&quot;]/b[@class=&quot;_720kb-datepicker-default-button&quot;]</value>
   </webElementProperties>
</WebElementEntity>
