<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_endDatePicker</name>
   <tag></tag>
   <elementGuidId>3b671366-278f-42eb-b818-a6e02e118f89</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>endDatePicker</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Choose a date</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>model.end_date</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validate ng-pristine ng-untouched ng-invalid ng-invalid-required-date ng-empty ng-valid-greater-than ng-valid-required</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>required</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eventDialog&quot;)/div[@class=&quot;ng-modal-dialog&quot;]/div[@class=&quot;ng-modal-dialog-content&quot;]/div[@class=&quot;edit-box row ng-scope&quot;]/div[@class=&quot;input-field col s12&quot;]/div[@class=&quot;col s8&quot;]/datepicker[@class=&quot;ng-isolate-scope&quot;]/input[@class=&quot;validate ng-pristine ng-untouched ng-invalid ng-invalid-required-date ng-empty ng-valid-greater-than ng-valid-required&quot;]</value>
   </webElementProperties>
</WebElementEntity>
